org: andreie
app: easy-feed
service: easy-feed-backend
variablesResolutionMode: 20210219

frameworkVersion: '2 || 3'

custom:
  dotenvVars: ${file(configs.js)}

outputs:
  dynamo-db-info: ${self.resources.Resources.EventsEasyFeedTable}
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-2
  tracing:
    lambda: true
    apiGateway: true
  logs:
    restApi: true
  httpApi:
    metrics: true # turn on detailed metrics
resources:
  Resources:
    EventsEasyFeedTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EasyFeedTest1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    EasyFeedApiGatewayDynamoRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: EastFeedApiGatewayDynamoRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Service: 'apigateway.amazonaws.com'
              Action:
                - 'sts:AssumeRole'
        Policies:
          - PolicyName: 'EasyFeedApiGatewayDynamoPolicy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - 'dynamodb:Query'
                  Resource:
                    - Fn::GetAtt: [EventsEasyFeedTable, Arn] 
    EasyFeedApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Description: "Api for easy feeds app"
        Name: !Sub "${self:app}"
    FeedsResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId:
          Ref: EasyFeedApi
        ParentId:
          Fn::GetAtt:
            - EasyFeedApi
            - RootResourceId
        PathPart: feeds
    FeedsAPI:
      Type: AWS::ApiGateway::Method
      Properties:
        HttpMethod: GET
        ResourceId: 
          Ref: FeedsResource
        RestApiId: 
          Ref: EasyFeedApi
        OperationName: "GetAllFeeds"
        AuthorizationType: NONE
        Integration:
          Type: AWS
          IntegrationHttpMethod: GET
          Uri: arn:aws:apigateway:us-east-2:dynamodb:action/Query
          Credentials: !GetAtt EasyFeedApiGatewayDynamoRole.Arn
          RequestTemplates:
            application/json: |
               #set($inputRoot = $input.path('$'))
                {
                    "TableName":"${self:resources.Resources.EventsEasyFeedTable.Properties.TableName}",
                    "PrimaryKey": "id",
                    "KeyConditionExpression": {
                        ":v1": {
                        "S":"$input.params('Hi')"
                    }
                }
          IntegrationResponses:
            - StatusCode: '200'
              ResponseParameters:
                method.response.header.Access-Control-Allow-Origin: "'*'"
              ResponseTemplates:
                application/json: '{}'
            - StatusCode: '400'
              SelectionPattern: "4\\d{2}"
              ResponseParameters:
                method.response.header.Access-Control-Allow-Origin: "'*'"
        MethodResponses:
          - StatusCode: '200'
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: true
            ResponseModels:
              application/json: Empty
          - StatusCode: '400'
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: true
            ResponseModels:
              application/json: Error




